# Generated by Django 6.0.5 on 2026-05-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=100, null=True, verbose_name='种类')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='重量')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='价格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
