# Generated by Django 6.0.5 on 2026-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称（种类）')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='英文名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='鱼的图片')),
                ('fish_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='稀有度')),
                ('stars', models.IntegerField(default=0, verbose_name='收藏星级')),
                ('rare_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='上星重量')),
                ('super_rare_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='蓝冠重量')),
                ('habitats', models.JSONField(blank=True, default=list, verbose_name='栖息水域')),
                ('fishing_method', models.CharField(blank=True, default='', max_length=100, verbose_name='钓法')),
                ('baits', models.JSONField(blank=True, default=list, verbose_name='推荐饵料')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
