# Generated by Django 6.0.5 on 2026-05-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('img', models.CharField(blank=True, default='', max_length=255, verbose_name='图片')),
                ('bait_type', models.CharField(blank=True, default='', max_length=100, verbose_name='形式')),
                ('buoyancy', models.CharField(blank=True, default='', max_length=50, verbose_name='浮力')),
                ('weight', models.CharField(blank=True, default='', max_length=50, verbose_name='质量')),
                ('water_weight', models.CharField(blank=True, default='', max_length=50, verbose_name='水中重量')),
                ('hook_size', models.CharField(blank=True, default='', max_length=100, verbose_name='鱼钩尺寸')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='品牌')),
                ('size', models.CharField(blank=True, default='', max_length=50, verbose_name='大小')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
