# Generated by Django 6.0.5 on 2026-05-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_bait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bait',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
        migrations.AddConstraint(
            model_name='bait',
            constraint=models.UniqueConstraint(fields=('name', 'bait_type'), name='unique_bait_name_type'),
        ),
    ]
