# Generated by Django 6.0.5 on 2026-05-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_bait_name_bait_unique_bait_name_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('img', models.CharField(blank=True, default='', max_length=255, verbose_name='图片')),
                ('lure_type', models.CharField(blank=True, default='', max_length=100, verbose_name='形式')),
                ('length', models.CharField(blank=True, default='', max_length=50, verbose_name='长度')),
                ('size', models.CharField(blank=True, default='', max_length=50, verbose_name='大小')),
                ('weight', models.CharField(blank=True, default='', max_length=50, verbose_name='质量')),
                ('hook_size', models.CharField(blank=True, default='', max_length=100, verbose_name='鱼钩尺寸')),
                ('unlock_skill', models.CharField(blank=True, default='', max_length=200, verbose_name='解锁技能')),
                ('hook_component', models.CharField(blank=True, default='', max_length=200, verbose_name='钓钩组件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'lure_type'), name='unique_lure_name_type')],
            },
        ),
    ]
