# Generated by Django 6.0.5 on 2026-05-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_lure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('img', models.CharField(blank=True, default='', max_length=255, verbose_name='图片')),
                ('rod_type', models.CharField(blank=True, default='', max_length=100, verbose_name='类型')),
                ('sensitivity', models.CharField(blank=True, default='', max_length=50, verbose_name='灵敏度')),
                ('structure', models.CharField(blank=True, default='', max_length=100, verbose_name='结构')),
                ('hardness', models.CharField(blank=True, default='', max_length=50, verbose_name='硬度')),
                ('capacity', models.CharField(blank=True, default='', max_length=50, verbose_name='能力')),
                ('length', models.CharField(blank=True, default='', max_length=50, verbose_name='长度')),
                ('strength', models.CharField(blank=True, default='', max_length=50, verbose_name='强度')),
                ('level_req', models.CharField(blank=True, default='', max_length=50, verbose_name='等级要求')),
                ('cast_weight', models.CharField(blank=True, default='', max_length=50, verbose_name='适配重')),
                ('weight', models.CharField(blank=True, default='', max_length=50, verbose_name='质量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'rod_type'), name='unique_rod_name_type')],
            },
        ),
    ]
