# Generated by Django 6.0.5 on 2026-05-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_rod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('img', models.CharField(blank=True, default='', max_length=255, verbose_name='图片')),
                ('reel_type', models.CharField(blank=True, default='', max_length=100, verbose_name='类型')),
                ('form', models.CharField(blank=True, default='', max_length=100, verbose_name='形式')),
                ('saltwater', models.CharField(blank=True, default='', max_length=50, verbose_name='防海水')),
                ('size', models.CharField(blank=True, default='', max_length=50, verbose_name='大小')),
                ('gear_ratio', models.CharField(blank=True, default='', max_length=50, verbose_name='传动比')),
                ('friction_brake', models.CharField(blank=True, default='', max_length=50, verbose_name='摩擦制动力')),
                ('line_retrieve_speed', models.CharField(blank=True, default='', max_length=50, verbose_name='回线速度')),
                ('max_drag', models.CharField(blank=True, default='', max_length=50, verbose_name='锁轮拉力')),
                ('cast_weight', models.CharField(blank=True, default='', max_length=100, verbose_name='测试/适配重')),
                ('line_capacity', models.TextField(blank=True, default='', verbose_name='线轴容量')),
                ('level_req', models.CharField(blank=True, default='', max_length=50, verbose_name='等级要求')),
                ('price_silver', models.CharField(blank=True, default='', max_length=50, verbose_name='银币')),
                ('price_gold', models.CharField(blank=True, default='', max_length=50, verbose_name='金币')),
                ('rating', models.CharField(blank=True, default='', max_length=50, verbose_name='评级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'reel_type'), name='unique_reel_name_type')],
            },
        ),
    ]
