# Generated by Django 6.0.5 on 2026-05-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_reel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('img', models.CharField(blank=True, default='', max_length=255, verbose_name='图片')),
                ('line_type', models.CharField(blank=True, default='', max_length=100, verbose_name='类型')),
                ('form', models.CharField(blank=True, default='', max_length=100, verbose_name='形式')),
                ('color', models.CharField(blank=True, default='', max_length=100, verbose_name='颜色')),
                ('length', models.CharField(blank=True, default='', max_length=100, verbose_name='长度')),
                ('max_load', models.CharField(blank=True, default='', max_length=200, verbose_name='限制')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='品牌')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'line_type'), name='unique_line_name_type')],
            },
        ),
    ]
