# Generated by Django 6.0.5 on 2026-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('img', models.CharField(blank=True, default='', max_length=255, verbose_name='图片')),
                ('hook_type', models.CharField(blank=True, default='', max_length=100, verbose_name='类型')),
                ('size', models.CharField(blank=True, default='', max_length=200, verbose_name='大小')),
                ('max_load', models.CharField(blank=True, default='', max_length=200, verbose_name='限制')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='品牌')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'hook_type'), name='unique_hook_name_type')],
            },
        ),
    ]
