# Generated by Django 6.0.5 on 2026-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_rig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groundbait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('img', models.CharField(blank=True, default='', max_length=255, verbose_name='图片')),
                ('groundbait_type', models.CharField(blank=True, default='', max_length=100, verbose_name='类型')),
                ('weight', models.CharField(blank=True, default='', max_length=100, verbose_name='重量')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='品牌')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'groundbait_type'), name='unique_groundbait_name_type')],
            },
        ),
    ]
